--create database bluemoondefinitivo;

use bluemoondefinitivo;

CREATE TABLE ALMACEN
( 
	ID_SEDE              char(15)  NOT NULL ,
	ID_ALMACEN           char(15)  NOT NULL ,
	NOMBRE_ALMACEN       varchar(40)  NOT NULL 
)
go



ALTER TABLE ALMACEN
	ADD CONSTRAINT XPKALMACEN PRIMARY KEY  CLUSTERED (ID_ALMACEN ASC)
go



CREATE TABLE BEBIDA
( 
	ID_BEBIDA            char(15)  NOT NULL ,
	NOMBRE_BEBIDA        varchar(40)  NOT NULL ,
	DESCRIPCION_BEBIDA   text  NULL ,
	PRECIO_BEBIDA        numeric(8,2)  NOT NULL ,
	ID_CATEGORIA_BEBIDA  char(15)  NULL 
)
go



ALTER TABLE BEBIDA
	ADD CONSTRAINT XPKBEBIDA PRIMARY KEY  CLUSTERED (ID_BEBIDA ASC)
go



CREATE TABLE CARGO
( 
	ID_CARGO             char(15)  NOT NULL ,
	NOMBRE_CARGO         varchar(30)  NOT NULL ,
	DESCRIPCION_CARGO    varchar(150)  NULL 
)
go



ALTER TABLE CARGO
	ADD CONSTRAINT XPKCARGO PRIMARY KEY  CLUSTERED (ID_CARGO ASC)
go



CREATE TABLE CATEGORIA_BEBIDA
( 
	ID_CATEGORIA_BEBIDA  char(15)  NOT NULL ,
	NOMBRE               varchar(20)  NULL ,
	ESTADO               varchar(20)  NULL ,
	DESCRIPCION          text  NULL 
)
go



ALTER TABLE CATEGORIA_BEBIDA
	ADD CONSTRAINT XPKCATEGORIA_BEBIDA PRIMARY KEY  CLUSTERED (ID_CATEGORIA_BEBIDA ASC)
go



CREATE TABLE CATEGORIA_PLATO
( 
	ID_CATEGORIA_PLATO   char(15)  NOT NULL ,
	NOMBRE               varchar(30)  NOT NULL ,
	DESCRIPCION          text  NULL ,
	ESTADO               varchar(40)  NULL 
)
go



ALTER TABLE CATEGORIA_PLATO
	ADD CONSTRAINT XPKCATEGORIA_PLATO PRIMARY KEY  CLUSTERED (ID_CATEGORIA_PLATO ASC)
go



CREATE TABLE CATEGORIA_PRODUCTO
( 
	ID_CATEGORIA         char(15)  NOT NULL ,
	NOMBRE_CATEGORIA     varchar(40)  NOT NULL ,
	DESCRIPCION_CATEGORIA text  NULL 
)
go



ALTER TABLE CATEGORIA_PRODUCTO
	ADD CONSTRAINT XPKCATEGORIA_INSUMO PRIMARY KEY  CLUSTERED (ID_CATEGORIA ASC)
go



CREATE TABLE CLIENTE
( 
	ID_CLIENTE           char(15)  NOT NULL ,
	DNI_CLIENTE          varchar(10)  NOT NULL ,
	NOMBRE_CLIENTE       varchar(40)  NOT NULL ,
	APELLIDOS_CLIENTE    varchar(40)  NOT NULL ,
	TELEFONO_CLIENTE     varchar(12)  NOT NULL ,
	RUC                  varchar(20)  NULL ,
	DIRECCION            text  NULL 
)
go



ALTER TABLE CLIENTE
	ADD CONSTRAINT XPKCLIENTE PRIMARY KEY  CLUSTERED (ID_CLIENTE ASC)
go



CREATE TABLE DET_BEBIDA_PEDIDO
( 
	CANTIDAD             integer  NULL ,
	PRECIO               numeric(8,2)  NULL ,
	ID_PEDIDO            char(15)  NOT NULL ,
	ID_BEBIDA            char(15)  NOT NULL 
)
go



ALTER TABLE DET_BEBIDA_PEDIDO
	ADD CONSTRAINT XPKDET_BEBIDA_PEDIDO PRIMARY KEY  CLUSTERED (ID_PEDIDO ASC,ID_BEBIDA ASC)
go



CREATE TABLE DET_DOCUMENTO_VENTA
( 
	ID_DOCUMENTO_VENTA   char(15)  NOT NULL ,
	ID_PLATO             char(15)  NOT NULL ,
	PRECIO               numeric(8,2)  NULL ,
	CANTIDAD             integer  NULL 
)
go



ALTER TABLE DET_DOCUMENTO_VENTA
	ADD CONSTRAINT XPKFACTURA PRIMARY KEY  CLUSTERED (ID_DOCUMENTO_VENTA ASC,ID_PLATO ASC)
go



CREATE TABLE DET_FACTURA_COMPRA
( 
	CANTIDAD             integer  NULL ,
	PRECIO               NUMERIC(8,2)  NULL ,
	ID_PRODUCTO          char(15)  NOT NULL ,
	ID_FACTURA_COMPRA    char(15)  NOT NULL 
)
go



ALTER TABLE DET_FACTURA_COMPRA
	ADD CONSTRAINT XPKDET_FACTURA_COMPRA PRIMARY KEY  CLUSTERED (ID_PRODUCTO ASC,ID_FACTURA_COMPRA ASC)
go



CREATE TABLE DET_GUIA_ENTRADA
( 
	CANTIDAD             integer  NULL ,
	ID_PRODUCTO          char(15)  NOT NULL ,
	ID_GUIA_ENTRADA      char(15)  NOT NULL 
)
go



ALTER TABLE DET_GUIA_ENTRADA
	ADD CONSTRAINT XPKDET_GUIA_ENTRADA PRIMARY KEY  CLUSTERED (ID_PRODUCTO ASC,ID_GUIA_ENTRADA ASC)
go



CREATE TABLE DET_GUIA_SALIDA
( 
	ID_PRODUCTO          char(15)  NOT NULL ,
	ID_GUIA_SALIDA       char(15)  NOT NULL ,
	CANTIDAD             integer  NULL 
)
go



ALTER TABLE DET_GUIA_SALIDA
	ADD CONSTRAINT XPKDET_GUIA_SALIDA PRIMARY KEY  CLUSTERED (ID_PRODUCTO ASC,ID_GUIA_SALIDA ASC)
go



CREATE TABLE DET_INVENTARIO
( 
	CANTIDAD             integer  NOT NULL ,
	ID_ALMACEN           char(15)  NOT NULL ,
	ID_PRODUCTO          char(15)  NOT NULL 
)
go



ALTER TABLE DET_INVENTARIO
	ADD CONSTRAINT XPKDET_INVENTARIO PRIMARY KEY  CLUSTERED (ID_PRODUCTO ASC,ID_ALMACEN ASC)
go



CREATE TABLE DET_PLATO_PEDIDO
( 
	CANTIDAD             integer  NOT NULL ,
	PRECIO               numeric(8,2)  NULL ,
	ID_PEDIDO            char(15)  NOT NULL ,
	ID_PLATO             char(15)  NOT NULL 
)
go



ALTER TABLE DET_PLATO_PEDIDO
	ADD CONSTRAINT XPKDET_VENTA_PEDIDO PRIMARY KEY  CLUSTERED (ID_PEDIDO ASC,ID_PLATO ASC)
go



CREATE TABLE DOCUMENTO_VENTA
( 
	ID_DOCUMENTO_VENTA   char(15)  NOT NULL ,
	TOTAL                numeric(8,2)  NOT NULL ,
	FECHA                datetime  NOT NULL ,
	SUBTOTAL             numeric(8,2)  NOT NULL ,
	ID_PERSONAL          char(15)  NOT NULL ,
	ID_CLIENTE           char(15)  NOT NULL ,
	IGV                  numeric(8,2)  NOT NULL ,
	TIPO_DOCUMENTO       varchar(30)  NULL 
)
go



ALTER TABLE DOCUMENTO_VENTA
	ADD CONSTRAINT XPKCOMPROBANTE PRIMARY KEY  CLUSTERED (ID_DOCUMENTO_VENTA ASC)
go



CREATE TABLE FACTURA_COMPRA
( 
	ID_PROVEEDOR         char(15)  NULL ,
	ID_FACTURA_COMPRA    char(15)  NOT NULL ,
	FECHA                datetime  NOT NULL ,
	IGV                  numeric(8,2)  NOT NULL ,
	SUBTOTAL             numeric(8,2)  NOT NULL ,
	TOTAL_FACTURA        numeric(8,2)  NOT NULL ,
	OBSERVACIONES        varchar(50)  NULL 
)
go



ALTER TABLE FACTURA_COMPRA
	ADD CONSTRAINT XPKDETALLE_COMPRA PRIMARY KEY  CLUSTERED (ID_FACTURA_COMPRA ASC)
go



CREATE TABLE GUIA_ENTRADA
( 
	ID_GUIA_ENTRADA      char(15)  NOT NULL ,
	FECHA                datetime  NOT NULL ,
	OBSERVACIONES        text  NULL ,
	ID_PROVEEDOR         char(15)  NOT NULL ,
	ID_FACTURA_COMPRA    char(15)  NOT NULL 
)
go



ALTER TABLE GUIA_ENTRADA
	ADD CONSTRAINT XPKGUIA_ENTRADA PRIMARY KEY  CLUSTERED (ID_GUIA_ENTRADA ASC)
go



CREATE TABLE GUIA_SALIDA
( 
	ID_GUIA_SALIDA       char(15)  NOT NULL ,
	FECHA                datetime  NULL ,
	OBSERVACIONES        text  NULL 
)
go



ALTER TABLE GUIA_SALIDA
	ADD CONSTRAINT XPKGUIA_SALIDA PRIMARY KEY  CLUSTERED (ID_GUIA_SALIDA ASC)
go



CREATE TABLE MESA
( 
	ID_MESA              char(15)  NOT NULL ,
	CAPACIDAD            integer  NOT NULL 
)
go



ALTER TABLE MESA
	ADD CONSTRAINT XPKMESA PRIMARY KEY  CLUSTERED (ID_MESA ASC)
go



CREATE TABLE PEDIDO
( 
	ID_PERSONAL          char(15)  NOT NULL ,
	ID_PEDIDO            char(15)  NOT NULL ,
	ID_MESA              char(15)  NULL ,
	TOTAL_PEDIDO         numeric(8,2)  NOT NULL ,
	FECHA_PEDIDO         datetime  NOT NULL ,
	ESTADO_PEDIDO        varchar(20)  NOT NULL ,
	ID_CLIENTE           char(15)  NULL 
)
go



ALTER TABLE PEDIDO
	ADD CONSTRAINT XPKPEDIDO PRIMARY KEY  CLUSTERED (ID_PEDIDO ASC)
go



CREATE TABLE PEDIDO_COMPRA
( 
	ID_PEDIDO_COMPRA     char(15)  NOT NULL ,
	ID_PROVEEDOR         char(15)  NULL ,
	ID_PRODUCTO          char(15)  NULL ,
	PRECIO               numeric(8,2)  NULL ,
	CANTIDAD             integer  NULL 
)
go



ALTER TABLE PEDIDO_COMPRA
	ADD CONSTRAINT XPKPEDIDO_COMPRA PRIMARY KEY  CLUSTERED (ID_PEDIDO_COMPRA ASC)
go



CREATE TABLE PERSONAL
( 
	ID_CARGO             char(15)  NOT NULL ,
	ID_PERSONAL          char(15)  NOT NULL ,
	DNI_PERSONAL         varchar(10)  NOT NULL ,
	NOMBRE_PERSONAL      varchar(50)  NOT NULL ,
	APELLIDO_PERSONAL    varchar(50)  NOT NULL ,
	TELEFONO_PERSONAL    varchar(12)  NOT NULL ,
	EMAIL_PERSONAL       varchar(30)  NULL ,
	ID_SEDE              char(15)  NOT NULL 
)
go



ALTER TABLE PERSONAL
	ADD CONSTRAINT XPKPERSONAL PRIMARY KEY  CLUSTERED (ID_PERSONAL ASC)
go



CREATE TABLE PLATO
( 
	ID_PLATO             char(15)  NOT NULL ,
	ID_CATEGORIA_PLATO   char(15)  NULL ,
	NOMBRE_PLATO         varchar(50)  NOT NULL ,
	PRECIO_PLATO         numeric(8,2)  NOT NULL ,
	DESCRIPCION_PLATO    text  NULL 
)
go



ALTER TABLE PLATO
	ADD CONSTRAINT XPKPLATO PRIMARY KEY  CLUSTERED (ID_PLATO ASC)
go



CREATE TABLE PRODUCTO
( 
	ID_PRODUCTO          char(15)  NOT NULL ,
	NOMBRE_PRODUCTO      varchar(40)  NOT NULL ,
	UNIDAD_MEDIDA        varchar(20)  NOT NULL ,
	ID_CATEGORIA         char(15)  NULL ,
	PRECIO_UNITARIO      numeric(8,2)  NOT NULL ,
	CANTIDAD_PRODUCTO    integer  NOT NULL 
)
go



ALTER TABLE PRODUCTO
	ADD CONSTRAINT XPKINSUMO PRIMARY KEY  CLUSTERED (ID_PRODUCTO ASC)
go



CREATE TABLE PROVEEDOR
( 
	ID_PROVEEDOR         char(15)  NOT NULL ,
	RUC_PROVEEDOR        varchar(30)  NOT NULL ,
	NOMBRE_PROVEEDOR     varchar(40)  NOT NULL ,
	DIRECCION_PROVEEDOR  text  NOT NULL ,
	TELEFONO_PROVEEDOR   varchar(15)  NOT NULL 
)
go



ALTER TABLE PROVEEDOR
	ADD CONSTRAINT XPKPROVEEDOR PRIMARY KEY  CLUSTERED (ID_PROVEEDOR ASC)
go



CREATE TABLE SEDE
( 
	ID_SEDE              char(15)  NOT NULL ,
	NOMBRE_SEDE          varchar(15)  NOT NULL ,
	DIRECCION_SEDE       text  NOT NULL ,
	TELEFONO_SEDE        varchar(12)  NOT NULL ,
	EMAIL_SEDE           text  NOT NULL 
)
go



ALTER TABLE SEDE
	ADD CONSTRAINT XPKSEDE PRIMARY KEY  CLUSTERED (ID_SEDE ASC)
go



CREATE TABLE USUARIO
( 
	ID_USUARIO           char(15)  NOT NULL ,
	NOMBRE_USUARIO       varchar(40)  NOT NULL ,
	CONTRASEÑA_USUARIO   varchar(30)  NOT NULL ,
	EMAIL_USUARIO        varchar(30)  NOT NULL ,
	TIPO_USUARIO         varchar(20)  NULL ,
	ID_PERSONAL          char(15)  NOT NULL 
)
go



ALTER TABLE USUARIO
	ADD CONSTRAINT XPKUSUARIO PRIMARY KEY  CLUSTERED (ID_USUARIO ASC)
go




ALTER TABLE ALMACEN
	ADD CONSTRAINT R_30 FOREIGN KEY (ID_SEDE) REFERENCES SEDE(ID_SEDE)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE BEBIDA
	ADD CONSTRAINT R_94 FOREIGN KEY (ID_CATEGORIA_BEBIDA) REFERENCES CATEGORIA_BEBIDA(ID_CATEGORIA_BEBIDA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DET_BEBIDA_PEDIDO
	ADD CONSTRAINT R_106 FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DET_BEBIDA_PEDIDO
	ADD CONSTRAINT R_107 FOREIGN KEY (ID_BEBIDA) REFERENCES BEBIDA(ID_BEBIDA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DET_DOCUMENTO_VENTA
	ADD CONSTRAINT R_83 FOREIGN KEY (ID_DOCUMENTO_VENTA) REFERENCES DOCUMENTO_VENTA(ID_DOCUMENTO_VENTA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DET_DOCUMENTO_VENTA
	ADD CONSTRAINT R_84 FOREIGN KEY (ID_PLATO) REFERENCES PLATO(ID_PLATO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DET_FACTURA_COMPRA
	ADD CONSTRAINT R_108 FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DET_FACTURA_COMPRA
	ADD CONSTRAINT R_109 FOREIGN KEY (ID_FACTURA_COMPRA) REFERENCES FACTURA_COMPRA(ID_FACTURA_COMPRA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DET_GUIA_ENTRADA
	ADD CONSTRAINT R_88 FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DET_GUIA_ENTRADA
	ADD CONSTRAINT R_92 FOREIGN KEY (ID_GUIA_ENTRADA) REFERENCES GUIA_ENTRADA(ID_GUIA_ENTRADA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DET_GUIA_SALIDA
	ADD CONSTRAINT R_96 FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DET_GUIA_SALIDA
	ADD CONSTRAINT R_97 FOREIGN KEY (ID_GUIA_SALIDA) REFERENCES GUIA_SALIDA(ID_GUIA_SALIDA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DET_INVENTARIO
	ADD CONSTRAINT R_86 FOREIGN KEY (ID_ALMACEN) REFERENCES ALMACEN(ID_ALMACEN)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DET_INVENTARIO
	ADD CONSTRAINT R_87 FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DET_PLATO_PEDIDO
	ADD CONSTRAINT R_80 FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DET_PLATO_PEDIDO
	ADD CONSTRAINT R_81 FOREIGN KEY (ID_PLATO) REFERENCES PLATO(ID_PLATO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DOCUMENTO_VENTA
	ADD CONSTRAINT R_76 FOREIGN KEY (ID_PERSONAL) REFERENCES PERSONAL(ID_PERSONAL)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DOCUMENTO_VENTA
	ADD CONSTRAINT R_78 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE FACTURA_COMPRA
	ADD CONSTRAINT R_31 FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE GUIA_ENTRADA
	ADD CONSTRAINT R_91 FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE GUIA_ENTRADA
	ADD CONSTRAINT R_93 FOREIGN KEY (ID_FACTURA_COMPRA) REFERENCES FACTURA_COMPRA(ID_FACTURA_COMPRA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE PEDIDO
	ADD CONSTRAINT R_16 FOREIGN KEY (ID_PERSONAL) REFERENCES PERSONAL(ID_PERSONAL)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE PEDIDO
	ADD CONSTRAINT R_27 FOREIGN KEY (ID_MESA) REFERENCES MESA(ID_MESA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE PEDIDO
	ADD CONSTRAINT R_111 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE PEDIDO_COMPRA
	ADD CONSTRAINT R_98 FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE PEDIDO_COMPRA
	ADD CONSTRAINT R_99 FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE PERSONAL
	ADD CONSTRAINT R_15 FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE PERSONAL
	ADD CONSTRAINT R_74 FOREIGN KEY (ID_SEDE) REFERENCES SEDE(ID_SEDE)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE PLATO
	ADD CONSTRAINT R_37 FOREIGN KEY (ID_CATEGORIA_PLATO) REFERENCES CATEGORIA_PLATO(ID_CATEGORIA_PLATO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE PRODUCTO
	ADD CONSTRAINT R_48 FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_PRODUCTO(ID_CATEGORIA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE USUARIO
	ADD CONSTRAINT R_100 FOREIGN KEY (ID_PERSONAL) REFERENCES PERSONAL(ID_PERSONAL)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go
